
package com.activeweb.css.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditScoreServiceImplService", targetNamespace = "http://service.css.activeweb.com/", wsdlLocation = "http://localhost:9712/CreditScoreService?wsdl")
public class CreditScoreServiceImplService
    extends Service
{

    private final static URL CREDITSCORESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITSCORESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CREDITSCORESERVICEIMPLSERVICE_QNAME = new QName("http://service.css.activeweb.com/", "CreditScoreServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9712/CreditScoreService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITSCORESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CREDITSCORESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CreditScoreServiceImplService() {
        super(__getWsdlLocation(), CREDITSCORESERVICEIMPLSERVICE_QNAME);
    }

    public CreditScoreServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITSCORESERVICEIMPLSERVICE_QNAME, features);
    }

    public CreditScoreServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CREDITSCORESERVICEIMPLSERVICE_QNAME);
    }

    public CreditScoreServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITSCORESERVICEIMPLSERVICE_QNAME, features);
    }

    public CreditScoreServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditScoreServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditScoreService
     */
    @WebEndpoint(name = "CreditScoreServiceImplPort")
    public CreditScoreService getCreditScoreServiceImplPort() {
        return super.getPort(new QName("http://service.css.activeweb.com/", "CreditScoreServiceImplPort"), CreditScoreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditScoreService
     */
    @WebEndpoint(name = "CreditScoreServiceImplPort")
    public CreditScoreService getCreditScoreServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.css.activeweb.com/", "CreditScoreServiceImplPort"), CreditScoreService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITSCORESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CREDITSCORESERVICEIMPLSERVICE_EXCEPTION;
        }
        return CREDITSCORESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
