
package com.activeweb.css.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditScoreService", targetNamespace = "http://service.css.activeweb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditScoreService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.activeweb.css.service.ScoreDetails
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreDetails", targetNamespace = "http://service.css.activeweb.com/", className = "com.activeweb.css.service.GetScoreDetails")
    @ResponseWrapper(localName = "getScoreDetailsResponse", targetNamespace = "http://service.css.activeweb.com/", className = "com.activeweb.css.service.GetScoreDetailsResponse")
    @Action(input = "http://service.css.activeweb.com/CreditScoreService/getScoreDetailsRequest", output = "http://service.css.activeweb.com/CreditScoreService/getScoreDetailsResponse")
    public ScoreDetails getScoreDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScore", targetNamespace = "http://service.css.activeweb.com/", className = "com.activeweb.css.service.GetScore")
    @ResponseWrapper(localName = "getScoreResponse", targetNamespace = "http://service.css.activeweb.com/", className = "com.activeweb.css.service.GetScoreResponse")
    @Action(input = "http://service.css.activeweb.com/CreditScoreService/getScoreRequest", output = "http://service.css.activeweb.com/CreditScoreService/getScoreResponse")
    public Integer getScore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
